### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by phatnhse** [TienVNguyen/FlicksProject#1]
:+1: Great work.You really pushed effort on this assignment. A few notes after checking out the code:
- Wow. You did all required and optional features. Respect!  
- Well organized packages and codes.
- Nice to see you used `Heterogenous Layout` inside `RecyclerView` with `CustomAdapter`. 
- Good use `Splash Screen` and handle connection error.
- Good to see you used `Endless Scrolling with AdapterViews and RecyclerView` and `SwipeToRefresh`.
- Nice UI.

Overall you did everything very well.I like your code. Hope to see you keep working harder for each assignment.

**Comment by TienVNguyen** [comment]
Hi @lazybee27102,

It's my pleasure that you like my code. Hope that I can provide much more better features in next assignments.

Thanks & Best Regards,
Tien Nguyen.
